---
title: "<center>Cardiovascular Diseases Risk Prediction<center>"
author: "<center>rahul<center>"
date: "<center>`r Sys.Date()`<center>"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman

---

```{r import_packages, echo=FALSE, warning=FALSE, comment=NA, message=FALSE}
library(tidyverse)
library(ggplot2)
library(DT)
library(dplyr)
library(plotly)
library(psych)
```

```{r import_data, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
cvd_dataset <- read.delim("/home/rahul/Downloads/CVD_cleaned.xls", sep = ",", header = TRUE)
```

```{r stats, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
stats <- describe(cvd_dataset)
```

# **Description**

```{r stats_table, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
DT::datatable(stats)
```

```{r heart_disease, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_dataset_heart_disease <- as.data.frame(table(cvd_dataset['Heart_Disease']))
colnames(cvd_dataset_heart_disease)[2] <- c("Count")
```

# **Heart Disease**

```{r heart_disease_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_heart_disease_plot <- ggplot(data = cvd_dataset_heart_disease, aes(x = `Heart_Disease`, y=`Count`)) + geom_bar(stat = "identity", fill = "steelblue", color = "steelblue")
ggplotly(cvd_heart_disease_plot)
```

```{r general_health, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_general_health <- as.data.frame(table(cvd_dataset$General_Health))
colnames(cvd_datatset_general_health) <- c("General Health", "Count")
```

# **General Health**

```{r general_health_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_general_health_plot <- ggplot(data = cvd_datatset_general_health, aes(x = `General Health`, y=`Count`)) + geom_bar(stat = "identity", fill = "brown1", color = "brown1")
ggplotly(cvd_datatset_general_health_plot)
```

```{r checkup, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_checkup <- as.data.frame(table(cvd_dataset$Checkup))
colnames(cvd_datatset_checkup) <- c("Checkup", "Count")
```

# **Checkup**

```{r checkup_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_checkup_plot <- ggplot(data = cvd_datatset_checkup, aes(x = `Checkup`, y=`Count`)) + geom_bar(stat = "identity", fill = "darkorchid4", color = "darkorchid4")
ggplotly(cvd_datatset_checkup_plot)
```

# **Skin Cancer**

```{r skin_cancer, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_skin_cancer <- as.data.frame(table(cvd_dataset$Skin_Cancer))
colnames(cvd_datatset_skin_cancer) <- c("Skin Cancer", "Count")
```


```{r skin_cancer_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_skin_cancer_plot <- ggplot(data = cvd_datatset_skin_cancer, aes(x = `Skin Cancer`, y=`Count`)) + geom_bar(stat = "identity", fill = "olivedrab", color = "olivedrab")
ggplotly(cvd_datatset_skin_cancer_plot)
```

# **Exercise**

```{r exercise, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_exercise <- as.data.frame(table(cvd_dataset$Exercise))
colnames(cvd_datatset_exercise) <- c("Exercise", "Count")
```


```{r exercise_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_exercise_plot <- ggplot(data = cvd_datatset_exercise, aes(x = `Exercise`, y = `Count`)) + geom_bar(stat = "identity", fill = "darkorange2", color = "darkorange2")
ggplotly(cvd_datatset_exercise_plot)
```



# **Other Cancer**

```{r other_cancer, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_other_cancer <- as.data.frame(table(cvd_dataset$Other_Cancer))
colnames(cvd_datatset_other_cancer) <- c("Other Cancer", "Count")
```


```{r other_cancer_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_other_cancer_plot <- ggplot(data = cvd_datatset_other_cancer, aes(x = `Other Cancer`, y = `Count`)) + geom_bar(stat = "identity", fill = "yellow3", color = "yellow3")
ggplotly(cvd_datatset_other_cancer_plot)
```

# **Depression**

```{r depression, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_depression <- as.data.frame(table(cvd_dataset$Depression))
colnames(cvd_datatset_depression) <- c("Depression", "Count")
```


```{r depression_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_depression_plot <- ggplot(data = cvd_datatset_depression, aes(x = `Depression`, y = `Count`)) + geom_bar(stat = "identity", fill = "peru", color = "peru")
ggplotly(cvd_datatset_depression_plot)
```

# **Diabetes**

```{r diabetes, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_diabetes <- as.data.frame(table(cvd_dataset$Diabetes))
colnames(cvd_datatset_diabetes) <- c("Diabetes", "Count")
```


```{r diabetes_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_diabetes_plot <- ggplot(data = cvd_datatset_diabetes, aes(x = `Diabetes`, y =`Count`)) + geom_bar(stat = "identity", fill = "wheat4", color = "wheat4")
ggplotly(cvd_datatset_diabetes_plot)
```

# **Arthritis**

```{r arthritis, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_arthritis <- as.data.frame(table(cvd_dataset$Arthritis))
colnames(cvd_datatset_arthritis) <- c("Arthritis", "Count")
```


```{r arthritis_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_arthritis_plot <- ggplot(data = cvd_datatset_arthritis, aes(x = `Arthritis`, y = `Count`)) + geom_bar(stat = "identity", fill = "seagreen4", color = "seagreen4")
ggplotly(cvd_datatset_arthritis_plot)
```

# **Sex**

```{r sex, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_sex <- as.data.frame(table(cvd_dataset$Sex))
colnames(cvd_datatset_sex) <- c("Sex", "Count")
```


```{r sex_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_sex_plot <- ggplot(data = cvd_datatset_sex, aes(x = `Sex`, y = `Count`)) + geom_bar(stat = "identity", fill = "burlywood2", color = "burlywood2")
ggplotly(cvd_datatset_sex_plot)
```

# **Age Category**

```{r age_category, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_age_category <- as.data.frame(table(cvd_dataset$Age_Category))
colnames(cvd_datatset_age_category) <- c("Age_Category", "Count")
```


```{r age_category_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_age_category_plot <- ggplot(data = cvd_datatset_age_category, aes(x = `Age_Category`, y = `Count`)) + geom_bar(stat = "identity", fill = "slategrey", color = "slategrey")
ggplotly(cvd_datatset_age_category_plot)
```

# **Height**


```{r height, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_height <- as.data.frame(table(cvd_dataset$Height_.cm.))
colnames(cvd_datatset_height) <- c("Height_(cm)", "Count")
cvd_datatset_height$`Height_(cm)` <- as.numeric(cvd_datatset_height$`Height_(cm)`)
cvd_datatset_height$Count <- as.numeric(cvd_datatset_height$Count)
```

```{r height_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_height_plot <- ggplot(data = cvd_datatset_height, aes(x = `Height_(cm)`, y = `Count`)) + geom_bar(stat = "identity", fill = "tomato4", color = "tomato4")
ggplotly(cvd_datatset_height_plot)
```

# **Weight_(kg)**

```{r weight, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_weight <- as.data.frame(table(cvd_dataset$Weight_.kg.))
colnames(cvd_datatset_weight) <- c("Weight_.kg.", "Count")
cvd_datatset_weight$Weight_.kg. <- as.numeric(cvd_datatset_weight$Weight_.kg.)
cvd_datatset_weight$Count <- as.numeric(cvd_datatset_weight$Count)
```

```{r weight_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_weight_plot <- ggplot(data = cvd_datatset_weight, aes(x = `Weight_.kg.`, y=`Count`)) + geom_bar(stat = "identity", fill = "aquamarine4", color = "aquamarine4")
ggplotly(cvd_datatset_weight_plot)
```

# **BMI**

```{r BMI, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_BMI <- as.data.frame(table(cvd_dataset$BMI))
colnames(cvd_datatset_BMI) <- c("BMI", "Count")
cvd_datatset_BMI$BMI <- as.numeric(cvd_datatset_BMI$BMI)
cvd_datatset_BMI$Count <- as.numeric(cvd_datatset_BMI$Count)
```


```{r BMI_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_BMI_plot <- ggplot(data = cvd_datatset_BMI, aes(x = `BMI`, y=`Count`)) + geom_bar(stat = "identity", fill = "darkgreen", color = "darkgreen")
ggplotly(cvd_datatset_BMI_plot)
```


# **Smoking History**

```{r smoking, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_smoking <- as.data.frame(table(cvd_dataset$Smoking_History))
colnames(cvd_datatset_smoking) <- c("Smoking History", "Count")
```

```{r smoking_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_smoking_plot <- ggplot(data = cvd_datatset_smoking, aes(x = `Smoking History`, y=`Count`)) + geom_bar(stat = "identity", fill = "red", color = "red")
ggplotly(cvd_datatset_smoking_plot)
```


# **Alcohol Consumption**

```{r alcohol_consumption, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_alcohol <- as.data.frame(table(cvd_dataset$Alcohol_Consumption))
colnames(cvd_datatset_alcohol) <- c("Alcohol Consumption", "Count")
```

```{r alcohol_consumption_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_alcohol_consumption_plot <- ggplot(data = cvd_datatset_alcohol, aes(x = `Alcohol Consumption`, y=`Count`)) + geom_bar(stat = "identity", fill = "darkslategray", color = "darkslategray")
ggplotly(cvd_datatset_alcohol_consumption_plot)
```

# **Fruit Consumption**

```{r fruit_consumption, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_fruit_consumption <- as.data.frame(table(cvd_dataset$Fruit_Consumption))
colnames(cvd_datatset_fruit_consumption) <- c("Fruit Consumption", "Count")
cvd_datatset_fruit_consumption$`Fruit Consumption` <- as.numeric(cvd_datatset_fruit_consumption$`Fruit Consumption`)
cvd_datatset_fruit_consumption$Count <- as.numeric(cvd_datatset_fruit_consumption$Count)
```

```{r fruit_consumption_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_fruit_consumption_plot <- ggplot(data = cvd_datatset_fruit_consumption, aes(x = `Fruit Consumption`, y=`Count`)) + geom_bar(stat = "identity", fill = "deeppink4", color = "deeppink4")
ggplotly(cvd_datatset_fruit_consumption_plot)
```

# **Green Vegetable Consumption**


```{r green_vegetable_consumption, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_green_vegetable_consumption <- as.data.frame(table(cvd_dataset$Green_Vegetables_Consumption))
colnames(cvd_datatset_green_vegetable_consumption) <- c("Green Vegetables Consumption", "Count")
cvd_datatset_green_vegetable_consumption$`Green Vegetables Consumption` <- as.numeric(cvd_datatset_green_vegetable_consumption$`Green Vegetables Consumption`)
cvd_datatset_green_vegetable_consumption$Count <- as.numeric(cvd_datatset_green_vegetable_consumption$Count)
```

```{r green_vegetable_consumption_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_green_vegetable_consumption_plot <- ggplot(data = cvd_datatset_green_vegetable_consumption, aes(x = `Green Vegetables Consumption`, y=`Count`)) + geom_bar(stat = "identity", fill = "blue", color = "blue")
ggplotly(cvd_datatset_green_vegetable_consumption_plot)
```

# **Fried Potato Consumption**

```{r fried_potato_consumption, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
cvd_datatset_fried_potato_consumption <- as.data.frame(table(cvd_dataset$FriedPotato_Consumption))
colnames(cvd_datatset_fried_potato_consumption) <- c("Fried Potato Consumption", "Count")
cvd_datatset_fried_potato_consumption$`Fried Potato Consumption` <- as.numeric(cvd_datatset_fried_potato_consumption$`Fried Potato Consumption`)
cvd_datatset_fried_potato_consumption$Count <- as.numeric(cvd_datatset_fried_potato_consumption$Count)
```

```{r fried_potato_consumption_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
options(scipen = 999)
cvd_datatset_fried_potato_consumption_plot <- ggplot(data = cvd_datatset_fried_potato_consumption, aes(x = `Fried Potato Consumption`, y=`Count`)) + geom_bar(stat = "identity", fill = "darkseagreen", color = "darkseagreen")
ggplotly(cvd_datatset_fried_potato_consumption_plot)
```
